language: java
jdk: oraclejdk8
dist: trusty
sudo: required

addons:
  chrome: stable


env:
  global:
    - WEBAPPDIR=webapp

before_install:
  - sudo sh -c 'echo "deb https://packages.atlassian.com/atlassian-sdk-deb stable contrib" >>/etc/apt/sources.list'
  - wget https://packages.atlassian.com/api/gpg/key/public
  - sudo apt-key add public
  - sudo apt-get update
  - sudo apt-get install atlassian-plugin-sdk
  - atlas-version
install:
  - echo In Install

before_script:
  - echo In Before Script

script:
  - atlas-package -Dob.ui.deps -Dob.ui -Dob.ui.tests

cache:
  directories:
    - $HOME/.m2
    - $WEBAPPDIR/node_modules

